[WIP] Add Link to MovieSlide
Currently causes Typescript Error TS2322 and cannot swipe across carousel as releasing click causes link to be activated. Going back also reset carousel to default position